# **TensorFlow**
### This is the first practice of tensorflow. To start with I will cover up the four points with describtion and the code.<br>
1- Like most of the launguages, we will first print *"Hello World"* through tensor flow.<br>
2- Printing *shape and rank* of different tensorflow constant.<br>
3- Coreprogram structure- *adding two variables in the tensorflow.*<br>
4- Placeholders - *Accepting external inputs into our models.* <br>

In [52]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import numpy as np
import tensorflow as tf
print('Package imported')

Package imported


Let's print `Hello, Tensorflow` using `TF` program

In [53]:
hello =  tf.constant('Hello,Tensorflow ')
#print (hello) #The output will be the description of hello variable

sess = tf.Session()
#For retrieving the value of the variable we have to create session in tensorflow
#print(sess.run(hello))
out = (tf.Session().run(hello)) #encoded to utf-8 and now it's a bytes object.
print(out.decode('utf8')) #DEcoding back to the string

Hello,Tensorflow 


# TENSOR

__Tensor__ is the central unit of data in TF. It has two properties:

 - Shape - a tuple of integers speccifying the array length along each dimension.
 - Rank - number of dimension
 
 `Tensforflow` uses numpy values to represent tensor values.

In [54]:
ex_tensor = tf.constant(3)
#print(tf.shape(ex_tensor))
#print(tf.rank(ex_tensor))
print(ex_tensor)

Tensor("Const_39:0", shape=(), dtype=int32)


In [55]:
ex_tensor = tf.constant([1, 2, 3])
print(ex_tensor)
mat =(sess.run(ex_tensor))
print(mat)

Tensor("Const_40:0", shape=(3,), dtype=int32)
[1 2 3]


In [56]:
ex_tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print(ex_tensor)
print(tf.Session().run(ex_tensor))

Tensor("Const_41:0", shape=(2, 3), dtype=int32)
[[1 2 3]
 [4 5 6]]


# TF Core Program Structure
Tensorflow core program consist of two discrete sections:

 - Building the computational graph(a tf.Graph)
 - Running the computational graph (using tf. Session)
 
## Graph
A computational fraph is a series of tensorflow operations arranged into graph.
The graph is composed of two type of object.

1. __Operations__ (or "ops"): THe nodes of graph.Operation describes calculations that produce and consume tensors.
2. __Tensors__ :  The edges in the graph. These represent the values that will flow through graph. Most Tensorflow functions return `tf.Tensors`


In [57]:
a = tf.constant([1, 2])
b = tf.constant([3, 4])
total = a + b
print(tf.Session().run(a))
print(tf.Session().run(b))
print(tf.Session().run(total))

[1 2]
[3 4]
[4 6]


## Session
To evaluate tensors, instantiate a `tf.session` object , informally known as a __session__. A session encapsulates the state of Tensorflow runtime and runs the tenserflow operations. If a `tf.graph` is like a `.py` file, a `tf.Session` is like a python executable.  

## Placeholders

A graph can be parameterized to accept external inputs, known as placeholders. A placeholder is a promise to provide a value later , like a function argument.

In [59]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x * y
#feed_dict argument of run method to feed the concrete values to the placeholders
print(sess.run(z, feed_dict={x:3, y:4}))
print(tf.Session().run(z, feed_dict={x:[1,2], y:[4,5]}))

12.0
[ 4. 10.]
